Add relative date calculations to date template variables
srg-kostyrko/obsidian-journal pull request #43
Opened 2024-04-15 17:19 UTC by arnoesterhuizen

resolves #41

Feature inspired and based off of code from liamcain/obsidian-periodic-notes

2024-04-16 06:12 UTC, srg-kostyrko commented
Thank you for your contribution.
Could you please also add information about this feature to `Variable reference` modal in `src/settings/ui/variable-reference.ts` and update readme

2024-04-16 09:51 UTC, arnoesterhuizen commented
Thanks for pointing out where I missed an update. I've updated the code; anything else I can add to make this easy to use?

I'm a novice when it gets to plugin development, so thanks for helping me get some experience :)

2024-04-16 13:34 UTC, srg-kostyrko requested changes
One small correction in descriptions and it will be good to go

2024-04-16 13:34 UTC, srg-kostyrko commented on README.md
> +- `{{start_date}}` - first day of week, month, quarter, year or interval depending on note type, formatted using date format from settings, format can be overridden using following syntax `{{start_da
it is capital `M` for month (lower case `m` is for minutes, please update in other file as well

2024-04-17 08:59 UTC, arnoesterhuizen commented
I've pushed a tweak to the readme and settings UI, and rather than writing a whole paragraph in a small space, included links to the momentjs reference. Hopefully this should make it easy to understand without cluttering the interface.

2024-04-17 12:26 UTC, srg-kostyrko approved these changes

2024-04-17 12:26 UTC, merged